package:
  name: hmmcdr
  version: "0.2.0"

source:
  url: https://files.pythonhosted.org/packages/f2/cc/af8c10941c081719f91770fcd14c9767bdfda1a899684dac7b22e3cf0840/hmmcdr-0.2.0.tar.gz
  sha256: 714588cd016d3be7d4457a801904d5054329c7bb514ace2814eae7668759bb08

build:
  noarch: python
  script: "${PYTHON} -m pip install --no-deps --ignore-installed ."

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  build:
    - setuptools
  run:
    - python >=3.7
    - pandas >=1.3.5
    - numpy >=1.21.5
    - pybedtools >=0.8.1  # Ensure bioconda channel is used
    - hmmlearn >=0.3.0    # Ensure conda-forge channel is used

test:
  imports:
    - hmmCDR

about:
  home: https://github.com/jmenendez98/hmmCDR
  license: MIT
  summary: Find CDR locations using bedmethyl file and CenSat annotations.

extra:
  identifiers:
    - biotools:hmmCDR
  keywords:
    - bioinformatics
    - genomics
    - centromeres
    - methylation
