{% set name = "hmmcdr" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: .

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8,<3.13
    - pip
    - setuptools
  build:
    - setuptools
  run:
    - python >=3.8,<3.13
    - numpy >=1.21.5
    - hmmlearn >=0.3.0    # Ensure conda-forge channel is used

test:
  imports:
    - hmmCDR

about:
  home: https://github.com/jmenendez98/hmmCDR
  license: MIT
  summary: Use HMM to find CDRs from bedmethyl and CenSat annotation files.

extra:
  recipe-maintainers:
    - jmmenend
  identifiers:
    - biotools:hmmCDR
  keywords:
    - bioinformatics
    - genomics
    - centromeres
    - methylation