{% set name = "centrodip" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: .

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8,<3.13
    - pip
    - setuptools
  build:
    - setuptools
  run:
    - python >=3.8,<3.13
    - numpy >=1.21.5
    - scipy >=1.7.3

test:
  imports:
    - centrodip

about:
  home: https://github.com/jmenendez98/centrodip
  license: MIT
  summary: Find hypomethylated regions in centromeres

extra:
  recipe-maintainers:
    - jmmenend
  identifiers:
    - biotools:centrodip
  keywords:
    - bioinformatics
    - genomics
    - centromeres
    - methylation